name: Build and Run Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: '3.12'

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh


      - name: Install dependencies
        run: uv sync

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 my-app:latest

      # 5. Run tests
      - name: Run tests
        run: uv run pytest